# Change these first
owner: Sulstice # Your GitHub organization or username, where this repository lives
repo: Uptime-Medical-Informatics # The name of this repository

sites:
  - name: Zinc 15
    url: https://zinc15.docking.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: medicinedb.org
  name: Medical Informatic Database Statuses
  introTitle: "Website Status of Medical Informatic Databases"
  introMessage: Welcome to the endpoint monitor of live databases. 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
 
