# Change these first
owner: Sulstice # Your GitHub organization or username, where this repository lives
repo: Uptime-Medical-Informatics # The name of this repository

sites:
  - name: Center for Invivo Microscopy
    url: http://www.civm.duhs.duke.edu/devatlas/ 
  - name: Embrionic and Neonatal Mouse
    url: http://www.civm.duhs.duke.edu/devatlas/UserGuide.pdf
  - name: LONI image data archive
    url: https://ida.loni.usc.edu/services/Menu/IdaData.jsp?project=
  - name: Collaborative Informatics and Neuroimaging Suite 
    url: https://portal.mrn.org/micis/index.php?subsite=dx
  - name: The Cancer Imaging Archive
    url: http://www.cancerimagingarchive.net/
  - name: Alzheimer’s Disease Neuroimaging Initiative
    url: http://adni.loni.ucla.edu/
  - name: The Open Access Series of Imaging Studies
    url: http://www.oasis-brains.org/
  - name: Breast Cancer Digital Repository
    url: https://bcdr.eu/
  - name: DDSM Digital Database for Screening Mammography
    url: http://marathon.csee.usf.edu/Mammography/Database.html
  - name: The Mammographic Image Analysis Society (MIAS) mini-database
    url: http://peipa.essex.ac.uk/info/mias.html
  - name: NLM HyperDoc Visible Human Project color, CAT and MRI image samples 
    url: http://www.nlm.nih.gov/research/visible/visible_human.html
  - name: CT Scans for Colon Cancer
    url: https://wiki.cancerimagingarchive.net/display/Public/CT+COLONOGRAPHY#e88604ec5c654f60a897fa77906f88a6
  - name: UTA4: Breast Cancer Medical Imaging DICOM Files Dataset & Resources
    url: https://github.com/MIMBCD-UI/dataset-uta4-dicom
  - name: UTA7: Breast Cancer Medical Imaging DICOM Files Dataset & Resources 
    url: https://github.com/MIMBCD-UI/dataset-uta7-dicom
  - name: BCNB: Early Breast Cancer Core-Needle Biopsy WSI Dataset
    url: https://bupt-ai-cz.github.io/BCNB/, https://github.com/bupt-ai-cz/BALNMP#bcnb-dataset
  - name: The Cancer Genome Atlas
    url: https://tcga-data.nci.nih.gov/tcga/
  - name: Stanford Tissue Microarray Database 
    url: http://tma.im
  - name: MITOS dataset
    url: http://www.ipal.cnrs.fr/event/icpr-2012
  - name: Cancer Image Database
    url: https://emice.nci.nih.gov/caimage
  - name: DPA’s Whole Slide Imaging Repository
    url: https://digitalpathologyassociation.org/whole-slide-imaging-repository
  - name: ITK Analysis of Large Histology Datasets
    url: http://www.na-mic.org/Wiki/index.php/ITK_Analysis_of_Large_Histology_Datasets
  - name: Histology Photo Album
    url: http://www.histology-world.com/photoalbum/thumbnails.php?album=52
  - name: Slide Library of Virtual pathology, University of Leeds
    url: http://www.virtualpathology.leeds.ac.uk/
  - name: Aperio Images
    url: http://images.aperio.com/
  - name: HAPS Histology Image Database
    url: http://hapshistology.wikifoundry.com/
  - name: BDGP images from the FlyExpress database
    url:  www.flyexpress.net
  - name: The UCSB Bio-Segmentation Benchmark dataset
    url: http://www.bioimage.ucsb.edu/research/biosegmentation
  - name: Pap Smear database
    url: http://mde-lab.aegean.gr/index.php/downloads
  - name: Histology (CIMA) dataset
    url: http://cmp.felk.cvut.cz/~borovji3/?page=dataset
  - name: ANHIR dataset 
    url: https://anhir.grand-challenge.org/
  - name: Genome RNAi dataset
    url: hhttp://www.genomernai.org/
  - name: Chinese Hamster Ovary cells (CHO) dataset 
    url: http://www.chogenome.org/data.html
  - name: Locate Endogenus mouse sub-cellular organelles (END) database
    url: http://locate.imb.uq.edu.au/
  - name: 2D HeLa dataset (HeLa) dataset
    url: https://ome.grc.nia.nih.gov/iicbu2008/hela/index.html
  - name: Allen Brain Atlas
    url: http://www.brain-map.org/
  - name: 1000 Functional Connectomes Project 
    url: http://fcon_1000.projects.nitrc.org/
  - name: The Cell Centered Database
    url:  https://library.ucsd.edu/dc/collection/bb5940732k
  - name: The Encyclopedia of DNA Elements
    url: http://genome.ucsc.edu/ENCODE/ 
  - name: The Human Protein Atlas
    url: http://www.proteinatlas.org/
  - name: DRIVE: Digital Retinal Images for Vessel Extraction
    url: http://www.isi.uu.nl/Research/Databases/DRIVE/ 
  - name: El Salvador Atlas of Gastrointestinal VideoEndoscopy Images and Videos of hi-res of studies taken from Gastrointestinal Video endoscopy
    url: http://www.gastrointestinalatlas.com/
  - name: BCNB: Early Breast Cancer Core-Needle Biopsy WSI Dataset
    url: https://bupt-ai-cz.github.io/BCNB/, https://github.com/bupt-ai-cz/BALNMP#bcnb-dataset
  - name: DermNet - Skin disease atlas
    url: http://www.dermnet.com/
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: medicinedb.org
  name: Medical Informatic Database Statuses
  introTitle: "Website Status of Medical Informatic Databases"
  introMessage: Welcome to the endpoint monitor of live databases. 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
 
